const dom = {
    startBtn: document.querySelector('#btn-start'),
    inputMin: document.querySelector('#minValue'),
    inputMax: document.querySelector('#maxValue'),
    inputAttempts: document.querySelector('#attempts'),
    sectionStartPage: document.querySelector('.start-page'),
    sectionGamePage: document.querySelector('.game-page'),
    divGreetings: document.querySelector('.greetings'),
    totalNumbersOfAttempts: document.querySelector('.total-number-of-attempts'),
    generateBtn: document.querySelector('.btn-generate'),
    inputUser: document.querySelector('#userValue'),
    divOut: document.querySelector('.out'),
    divImg: document.querySelectorAll('.img'),
    remainingAttempts: document.querySelector('.remaining-attempts'),
    exitBtn: document.querySelector('.btn-exit'),
     blocksTextError:document.querySelectorAll('.error'),
     questionIcon:document.querySelector('.question'),
     instruction:document.querySelector('.instruction'),
     windowElement:document.querySelector('.window')
};